## 26 Feb Assignment

### Consider the below code to answer further questions:

### import numpy as np
### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
### array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Yes, there is a difference in both data types.
#### `list_` is a list object, and the elements inside it are strings. The data type is `list`.

#### `array_list` is a NumPy array created from `list_` object. The elements in `array_list` will also be stored as strings but the data type is `numpy.ndarray`

In [12]:
#Code:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print('Data type of list_',type(list_))
print('Data type of array_list',type(array_list))

Data type of list_ <class 'list'>
Data type of array_list <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [15]:
#Code:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))
print('-----------------------')
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
-----------------------
Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

### array_list = np.array(object = list_, dtype = int)

### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [16]:
#Code:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

print("Data types of elements in list_:")
for element in list_:
    print(type(element))
print('-----------------------')
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
-----------------------
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


#### Yes, there is a difference in both data types.
#### `list_` is a list object, and the elements inside it are strings. The data type is list.
#### `array_list` is a NumPy array created from list_ object. The elements in array_list will be now stored as integers because of `'dtype=int'` but the data type for `array_list` is numpy.ndarray

### Consider the below code to answer further questions:

### import numpy as np
### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
### num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size

In [23]:
#Code:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

print('Shape of Array:',np.shape(num_array))
print('Size of Array:',np.size(num_array))

Shape of Array: (2, 3)
Size of Array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [26]:
import numpy as np
arr=np.zeros([3,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
import numpy as np
arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
